name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message'
        required: true
        default: 'generated'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: conf/github-profile-3d-contrib.json
      - name: Set up Git
        run: |
          git config user.name "Adelio-IN"
          git config user.email "2024011862@office.cju.ac.kr"
      - name: Pull remote changes with rebase
        run: |
          git pull origin main --rebase || true
      - name: Commit & Push
        run: |
          git add -A .
          git commit -m "${{ github.event.inputs.commit_message }}" || echo "No changes to commit"
          git push origin main
